# -------------------
# build builder image
# -------------------

# FROM openjdk:8u275-jdk as builder
FROM openjdk:17-jdk-slim as builder

RUN apt-get update && \
    apt-get -y --no-install-recommends install apt-utils libxml2 git unzip wget

WORKDIR /opt/grobid

RUN mkdir -p dataseer-source grobid-home/models
COPY src dataseer-source/src
COPY settings.gradle dataseer-source/
COPY resources/config/server.yml dataseer-source/resources/config/server.yml
COPY resources/config/dataseer-ml.yml dataseer-source/resources/config/dataseer-ml.yml
COPY resources/models dataseer-source/resources/models
COPY resources/lexicon dataseer-source/resources/lexicon
COPY build.gradle dataseer-source/
COPY gradle.properties dataseer-source/
COPY gradle dataseer-source/gradle/
COPY gradlew dataseer-source/
#COPY .git dataseer-source/.git
#COPY localLibs dataseer-source/localLibs

# Preparing models
WORKDIR /opt/grobid/dataseer-source
RUN rm -rf /opt/grobid/grobid-home/models/*
RUN ./gradlew clean assemble -x shadowJar --no-daemon  --stacktrace --info
RUN ./gradlew copyModels  --no-daemon --info --stacktrace \
    && rm -f /opt/grobid/grobid-home/models/*.zip

# Preparing distribution
WORKDIR /opt/grobid
RUN unzip -o /opt/grobid/dataseer-source/build/distributions/dataseer-ml-0*.zip -d dataseer_distribution \
  && mv dataseer_distribution/dataseer-* dataseer-ml \
  && rm -rf /opt/grobid/dataseer-source/build

# -------------------
# build runtime image
# -------------------

FROM lfoppiano/grobid:0.8.0-full-slim as runtime

# setting locale is likely useless but to be sure
ENV LANG C.UTF-8

WORKDIR /opt/grobid
RUN rm -rf /opt/grobid/grobid-home/models/*-with_ELMo \
    && rm -rf /opt/grobid/grobid-service \
    && ln -sf dataseer-ml/resources/ resources

# the last command above is just a hack to make the lexicon loader working

COPY --from=builder /opt/grobid/grobid-home/models ./grobid-home/models
COPY --from=builder /opt/grobid/dataseer-ml ./dataseer-ml/
COPY --from=builder /opt/grobid/dataseer-source/resources/config/*.yml ./dataseer-ml/resources/config/
COPY --from=builder /opt/grobid/dataseer-source/resources/lexicon/ ./dataseer-ml/resources/lexicon/

RUN sed -i 's/^grobidHome:.*/grobidHome: \/opt\/grobid\/grobid-home/' dataseer-ml/resources/config/dataseer-ml.yml \
    && sed -i 's/^grobidHome:.*/grobidHome: \/opt\/grobid\/grobid-home/' dataseer-ml/resources/config/server.yml

COPY --from=builder /opt/grobid/dataseer-ml /opt/grobid/dataseer-ml

RUN python3 preload_embeddings.py --registry ./resources-registry.json --embedding word2vec

VOLUME ["/opt/grobid/grobid-home/tmp"]

ARG GROBID_VERSION
ENV GROBID_VERSION=${GROBID_VERSION:-latest}
ENV DATASEER_ML_OPTS "-Djavrua.library.path=/opt/grobid/grobid-home/lib/li-64:/usr/local/lib/python3.8/dist-packages/jep --add-opens java.base/java.lang=ALL-UNNAMED"

# WORKDIR /opt/grobid/dataseer-ml

CMD ["dataseer-ml/bin/dataseer-ml", "server", "dataseer-ml/resources/config/server.yml"]

LABEL \
    authors="The contributors" \
    org.label-schema.name="datastet" \
    org.label-schema.description="Image with DataStet service" \
    org.label-schema.url="https://github.com/DataSeer/datastet" \
    org.label-schema.version=${GROBID_VERSION}